apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-cowsay
  labels:
    app: gradio-cowsay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-cowsay
  template:
    metadata:
        labels:
          app: gradio-cowsay
    spec:
      containers:
        - name: gradio-cowsay
          image: ghcr.io/grycap/gradio_cowsay
          env:
            - name: oscar_endpoint
              value: "https://<oscar-public-domain>"
            - name: port
              value: "30001"
          ports:
            - name: web
              containerPort: 30001
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-gradio-cowsay  
spec:
  selector:
    app: gradio-gradio-cowsay
  ports:
    - protocol: TCP
      port: 9000
      name: service-port
      targetPort: 30001
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gradio-cowsay
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '999999'
spec:
  tls:
  - hosts:
    - cowsay.<public-domain>
    secretName: cowsay.<public-domain>
  rules:
  - host: cowsay.<public-domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-gradio-cowsay
            port:
              number: 9000
